{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wegooooo.sdk",
    "module": "test",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-1.0.aar",
          "url": "test-1.0.aar",
          "size": 32622,
          "sha512": "88c372a13ab76de83e87be1a433f0aa8ecd7a0ca01ba684e0f48a66f4cc368caf007e6aaa464ed83b989a52831088983bc88e2be232ef7582df7386fe480c1ce",
          "sha256": "bfec7fb7aa75cfc24c69a0a04d56ced845c3349f81579540e46c2c2cc7e4ed20",
          "sha1": "97aa993f0f42c1436fb3c8f0fd94d722073b5d60",
          "md5": "00c86ccbf9e08c16e55ccdf940947e5e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-1.0.aar",
          "url": "test-1.0.aar",
          "size": 32622,
          "sha512": "88c372a13ab76de83e87be1a433f0aa8ecd7a0ca01ba684e0f48a66f4cc368caf007e6aaa464ed83b989a52831088983bc88e2be232ef7582df7386fe480c1ce",
          "sha256": "bfec7fb7aa75cfc24c69a0a04d56ced845c3349f81579540e46c2c2cc7e4ed20",
          "sha1": "97aa993f0f42c1436fb3c8f0fd94d722073b5d60",
          "md5": "00c86ccbf9e08c16e55ccdf940947e5e"
        }
      ]
    }
  ]
}
