{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wegooooo.sdk",
    "module": "mnn",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mnn-0.0.1.aar",
          "url": "mnn-0.0.1.aar",
          "size": 22757542,
          "sha512": "9602d092c35afb8b3fa402f647ff6cb351398c7ae6db7dbf5b994e9edbcf68023cc410b2846c90f073e6f5ff47e2e30fc05ebef9bdfdc0e214dd55f7c5bd7d15",
          "sha256": "bd80421da3cc1e251474d3d71d23222bd87fed6a220bf7a1bde2796b3c1ee365",
          "sha1": "a044bea54543e4d1d08a7e0f77a567ecc98e2473",
          "md5": "9042974b96444ea673fc58cb310127fd"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mnn-0.0.1.aar",
          "url": "mnn-0.0.1.aar",
          "size": 22757542,
          "sha512": "9602d092c35afb8b3fa402f647ff6cb351398c7ae6db7dbf5b994e9edbcf68023cc410b2846c90f073e6f5ff47e2e30fc05ebef9bdfdc0e214dd55f7c5bd7d15",
          "sha256": "bd80421da3cc1e251474d3d71d23222bd87fed6a220bf7a1bde2796b3c1ee365",
          "sha1": "a044bea54543e4d1d08a7e0f77a567ecc98e2473",
          "md5": "9042974b96444ea673fc58cb310127fd"
        }
      ]
    }
  ]
}
