{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wegooooo.sdk",
    "module": "mnn",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mnn-0.0.3.aar",
          "url": "mnn-0.0.3.aar",
          "size": 18207468,
          "sha512": "281e29553dfa95b0d9e591aada3e6f8b1aeb2bd9fe028b5e77db830523043a9a81e3cc42ce94a37abfbfbdde358c0d4bd1c3c0703bd33f9aabf8cb407e42dc50",
          "sha256": "3a668aba601772047c4411899a688bdf1f3116b64e3082fc6a76fe6279e1aee3",
          "sha1": "9ef358319bb2f0f0c7c9476ff87084ab71c7424a",
          "md5": "2bb838cea644f537686aa020d2f3dae7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mnn-0.0.3.aar",
          "url": "mnn-0.0.3.aar",
          "size": 18207468,
          "sha512": "281e29553dfa95b0d9e591aada3e6f8b1aeb2bd9fe028b5e77db830523043a9a81e3cc42ce94a37abfbfbdde358c0d4bd1c3c0703bd33f9aabf8cb407e42dc50",
          "sha256": "3a668aba601772047c4411899a688bdf1f3116b64e3082fc6a76fe6279e1aee3",
          "sha1": "9ef358319bb2f0f0c7c9476ff87084ab71c7424a",
          "md5": "2bb838cea644f537686aa020d2f3dae7"
        }
      ]
    }
  ]
}
