{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wegooooo.sdk",
    "module": "mnn",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mnn-0.0.6.aar",
          "url": "mnn-0.0.6.aar",
          "size": 18211219,
          "sha512": "8831d5d81e5269a8b831f7c72142fe5ec231953902946720bfae5a7d0b1fe727a05512da4a2b46152c2c1c14d8c86f46a0241ef94a7d27dc50fda6f47f746c62",
          "sha256": "eef2cb8439fc344ea47561c5cf1c385f92ad5e6032c73b9329ed96392d0ecaf9",
          "sha1": "d5ee5796805ffeda94091f75784a74dca92cbdfa",
          "md5": "66e6fee49967d4065d9317ac27cc8f92"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mnn-0.0.6.aar",
          "url": "mnn-0.0.6.aar",
          "size": 18211219,
          "sha512": "8831d5d81e5269a8b831f7c72142fe5ec231953902946720bfae5a7d0b1fe727a05512da4a2b46152c2c1c14d8c86f46a0241ef94a7d27dc50fda6f47f746c62",
          "sha256": "eef2cb8439fc344ea47561c5cf1c385f92ad5e6032c73b9329ed96392d0ecaf9",
          "sha1": "d5ee5796805ffeda94091f75784a74dca92cbdfa",
          "md5": "66e6fee49967d4065d9317ac27cc8f92"
        }
      ]
    }
  ]
}
